Fix error in wok_log.error() in models/users.py
This patch avoids the following error when trying to create
an user that doesn't exist but its homedir does:

-----

Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

-----

Now the proper error message is being forwarded to the user.

Signed-off-by: Daniel Henrique Barboza <dhbarboza82@gmail.com>