SR-IOV fixes after hardware testing - model/interfaces.py
Fixes on issues found when testing SR-IOV in real CX4 hardware:

- Fixed argument reading of enable_sriov. Argument reading was wrong
and issuing the following error even in a proper usage:

  File "model/interfaces.py", line 134, in _mlx5_SRIOV_precheck
    if not args or 'num_vfs' not in args.keys():
AttributeError: 'int' object has no attribute 'keys'

- Task uri was wrong.

- Moved the 'add_config_to_mlx5_SRIOV_boot_script' to be executed
before the creating of config files.

- Changed the error message format to a more generic one. The task
is dealing with more than writing the SR-IOV system file.

i18n.py message GINNET0085E was changed to only have one argument,
following the error format change mentioned above.

Signed-off-by: Daniel Henrique Barboza <danielhb@linux.vnet.ibm.com>